apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: demo
  labels:
    app: service-a
spec:
  type: ClusterIP
  selector:
    app: service-a
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
